"""Single-page Flask app for generating random Australian profiles."""

import os

import csv
import io

from flask import Flask, Response, jsonify, render_template_string, request

from employee_generator import CSV_HEADERS, random_employee
from profile_generator import generate_profile

app = Flask(__name__)

HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Random Profile Generator</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #f0f4f8;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 2rem 1rem;
      color: #1a202c;
    }

    h1 {
      font-size: 2rem;
      font-weight: 700;
      color: #2b6cb0;
      margin-bottom: 0.25rem;
      text-align: center;
    }

    .subtitle {
      color: #718096;
      margin-bottom: 2rem;
      text-align: center;
    }


    .card {
      background: #fff;
      border-radius: 1rem;
      box-shadow: 0 4px 24px rgba(0,0,0,0.08);
      padding: 2rem;
      width: 100%;
      max-width: 680px;
    }

    .section-title {
      font-size: 0.75rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.08em;
      color: #a0aec0;
      margin: 1.5rem 0 0.75rem;
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 0.4rem;
    }
    .section-title:first-child { margin-top: 0; }

    .field-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 0.75rem 1.5rem;
    }

    .field { display: flex; flex-direction: column; gap: 0.2rem; }
    .field.full { grid-column: 1 / -1; }

    .field label {
      font-size: 0.72rem;
      font-weight: 600;
      color: #718096;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .field .value {
      font-size: 1rem;
      color: #1a202c;
      font-weight: 500;
      word-break: break-all;
      cursor: pointer;
      padding: 0.25rem 0.5rem;
      border-radius: 0.3rem;
      transition: background 0.15s;
    }
    .field .value:hover { background: #ebf8ff; }
    .field .value:active { background: #bee3f8; }

    .copy-hint {
      font-size: 0.7rem;
      color: #a0aec0;
      text-align: center;
      margin-top: 0.25rem;
    }

    .btn {
      display: block;
      width: 100%;
      margin-top: 2rem;
      padding: 0.85rem;
      background: linear-gradient(135deg, #3182ce, #2b6cb0);
      color: #fff;
      font-size: 1.05rem;
      font-weight: 600;
      border: none;
      border-radius: 0.6rem;
      cursor: pointer;
      transition: opacity 0.15s, transform 0.1s;
      letter-spacing: 0.02em;
    }
    .btn:hover { opacity: 0.92; }
    .btn:active { transform: scale(0.98); }
    .btn:disabled { opacity: 0.6; cursor: default; }

    .disclaimer {
      margin-top: 1.5rem;
      padding: 0.85rem 1rem;
      background: #fffbeb;
      border: 1px solid #f6e05e;
      border-radius: 0.5rem;
      font-size: 0.82rem;
      color: #744210;
      line-height: 1.5;
      max-width: 680px;
      width: 100%;
      text-align: center;
    }

    .disclaimer strong { color: #c05621; }

    .toast {
      position: fixed;
      bottom: 1.5rem;
      left: 50%;
      transform: translateX(-50%) translateY(100px);
      background: #2d3748;
      color: #fff;
      padding: 0.6rem 1.2rem;
      border-radius: 2rem;
      font-size: 0.85rem;
      transition: transform 0.25s ease;
      pointer-events: none;
      z-index: 100;
    }
    .toast.show { transform: translateX(-50%) translateY(0); }

    #loading { display: none; }
    .spin {
      display: inline-block;
      animation: spin 0.8s linear infinite;
    }
    @keyframes spin { to { transform: rotate(360deg); } }

    @media (max-width: 480px) {
      .field-grid { grid-template-columns: 1fr; }
      .field.full { grid-column: 1; }
    }
  </style>
</head>
<body>

  <h1>Profile Generator</h1>
  <p class="subtitle">Instant random Australian identity for testing &amp; demos</p>

  <div class="card" id="card">
    <p style="color:#a0aec0;text-align:center;padding:2rem 0;">
      Click <strong>Generate Profile</strong> to get started.
    </p>
  </div>

  <button class="btn" id="genBtn" onclick="generateProfile()">
    <span id="btnText">Generate Profile</span>
    <span id="loading" class="spin">⟳</span>
  </button>

  <div class="disclaimer">
    <strong>⚠️ Disclaimer:</strong> All profiles generated by this tool are
    entirely <strong>fictional and randomly generated</strong>. No real person
    is represented. Intended for software testing, demos, and development purposes only.
  </div>

  <div class="toast" id="toast">Copied to clipboard!</div>

<script>
  async function generateProfile() {
    const btn = document.getElementById('genBtn');
    const btnText = document.getElementById('btnText');
    const loading = document.getElementById('loading');

    btn.disabled = true;
    btnText.textContent = 'Generating…';
    loading.style.display = 'inline-block';

    try {
      const res = await fetch('/api/profile');
      const p = await res.json();
      renderProfile(p);
    } catch(e) {
      alert('Failed to generate profile. Please try again.');
    } finally {
      btn.disabled = false;
      btnText.textContent = 'Generate Another Profile';
      loading.style.display = 'none';
    }
  }

  function renderProfile(p) {
    const sections = [
      {
        title: 'Personal Information',
        fields: [
          { label: 'First Name', value: p.first_name },
          { label: 'Last Name', value: p.last_name },
          { label: 'Middle Name', value: p.middle_name || '—' },
          { label: 'Date of Birth', value: p.date_of_birth },
        ]
      },
      {
        title: 'Contact Details',
        fields: [
          { label: 'Email', value: p.email, full: true },
          { label: 'Phone', value: p.phone_number },
        ]
      },
      {
        title: 'Address',
        fields: [
          { label: 'Street', value: p.address_line_1, full: true },
          { label: 'Suburb', value: p.suburb },
          { label: 'State', value: p.state },
          { label: 'Postcode', value: p.postcode },
          { label: 'Country', value: p.country },
        ]
      },
      {
        title: 'Identity Documents',
        fields: [
          { label: 'Passport Number', value: p.passport_number },
          { label: 'Driver\'s Licence', value: p.drivers_licence },
          { label: 'Medicare Number', value: p.medicare_number },
          { label: 'Tax File Number (TFN)', value: p.tax_file_number },
        ]
      }
    ];

    let html = '';
    for (const section of sections) {
      html += `<div class="section-title">${section.title}</div>`;
      html += '<div class="field-grid">';
      for (const f of section.fields) {
        html += `<div class="field${f.full ? ' full' : ''}">
          <label>${f.label}</label>
          <span class="value" title="Click to copy" onclick="copyVal(this)">${f.value}</span>
        </div>`;
      }
      html += '</div>';
    }
    html += '<p class="copy-hint">Click any value to copy it</p>';
    document.getElementById('card').innerHTML = html;
  }

  function copyVal(el) {
    navigator.clipboard.writeText(el.textContent).then(() => showToast());
  }

  function showToast() {
    const t = document.getElementById('toast');
    t.classList.add('show');
    setTimeout(() => t.classList.remove('show'), 1800);
  }
</script>
</body>
</html>"""


@app.route("/")
def index():
    return render_template_string(HTML)


@app.route("/api/profile")
def api_profile():
    return jsonify(generate_profile())


@app.route("/api/employees")
def api_employees():
    try:
        count = max(1, min(5000, int(request.args.get("count", 10))))
    except (ValueError, TypeError):
        count = 10
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=CSV_HEADERS)
    writer.writeheader()
    for _ in range(count):
        writer.writerow(random_employee())
    return Response(
        buf.getvalue(),
        mimetype="text/csv",
        headers={"Content-Disposition": f'attachment; filename="employees_{count}.csv"'},
    )


if __name__ == "__main__":
    debug = os.getenv("FLASK_DEBUG", "false").lower() == "true"
    app.run(debug=debug, port=5000)
